<a href="https://colab.research.google.com/github/Scwain/Numerical-Methods/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Determinants of Matrix

##Determinants of Matrix using numpy.linalg.det

In [17]:
import numpy as np
print("For Array A")
A = np.array([
    [1,2,-1],
    [4,6,-2],
    [-1,3,3]
])
print(A)
print("LinAlg For A")
print(round(np.linalg.det(A)))


For Array A
[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
LinAlg For A
-14
